//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_gulSistemEntities : DbContext
    {
        public db_gulSistemEntities()
            : base("name=db_gulSistemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HbKayitBazliMuhasebeServisi> HbKayitBazliMuhasebeServisis { get; set; }
        public virtual DbSet<iptalEdilenSiparisler> iptalEdilenSiparislers { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<picturesAltUrun> picturesAltUruns { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_description> product_description { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_agirlik> tbl_agirlik { get; set; }
        public virtual DbSet<tbl_altKategori> tbl_altKategori { get; set; }
        public virtual DbSet<tbl_altKategority> tbl_altKategority { get; set; }
        public virtual DbSet<tbl_altUrunler> tbl_altUrunler { get; set; }
        public virtual DbSet<tbl_buybox> tbl_buybox { get; set; }
        public virtual DbSet<tbl_buyboxTy> tbl_buyboxTy { get; set; }
        public virtual DbSet<tbl_cargo> tbl_cargo { get; set; }
        public virtual DbSet<Tbl_cikis> Tbl_cikis { get; set; }
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_çop> tbl_çop { get; set; }
        public virtual DbSet<tbl_digerSatici> tbl_digerSatici { get; set; }
        public virtual DbSet<tbl_digerSaticiFiyat> tbl_digerSaticiFiyat { get; set; }
        public virtual DbSet<tbl_digerSaticiResim> tbl_digerSaticiResim { get; set; }
        public virtual DbSet<tbl_digerSaticiTagList> tbl_digerSaticiTagList { get; set; }
        public virtual DbSet<tbl_digerSaticiUrun> tbl_digerSaticiUrun { get; set; }
        public virtual DbSet<tbl_digerUrunSaticiNm> tbl_digerUrunSaticiNm { get; set; }
        public virtual DbSet<tbl_durum> tbl_durum { get; set; }
        public virtual DbSet<tbl_fatura> tbl_fatura { get; set; }
        public virtual DbSet<tbl_guncelFiyat> tbl_guncelFiyat { get; set; }
        public virtual DbSet<tbl_hacim> tbl_hacim { get; set; }
        public virtual DbSet<tbl_hizliEkleHb> tbl_hizliEkleHb { get; set; }
        public virtual DbSet<tbl_kategori> tbl_kategori { get; set; }
        public virtual DbSet<tbl_kategorilerHb> tbl_kategorilerHb { get; set; }
        public virtual DbSet<tbl_kategoriTy> tbl_kategoriTy { get; set; }
        public virtual DbSet<tbl_kullanici> tbl_kullanici { get; set; }
        public virtual DbSet<tbl_kullohbuybox> tbl_kullohbuybox { get; set; }
        public virtual DbSet<tbl_log> tbl_log { get; set; }
        public virtual DbSet<tbl_logbuybux> tbl_logbuybux { get; set; }
        public virtual DbSet<tbl_magazaFiyatlari> tbl_magazaFiyatlari { get; set; }
        public virtual DbSet<tbl_marka> tbl_marka { get; set; }
        public virtual DbSet<tbl_markaTy> tbl_markaTy { get; set; }
        public virtual DbSet<tbl_model> tbl_model { get; set; }
        public virtual DbSet<tbl_musteri> tbl_musteri { get; set; }
        public virtual DbSet<tbl_musteriler> tbl_musteriler { get; set; }
        public virtual DbSet<tbl_numara> tbl_numara { get; set; }
        public virtual DbSet<tbl_order> tbl_order { get; set; }
        public virtual DbSet<tbl_ortakSiparis> tbl_ortakSiparis { get; set; }
        public virtual DbSet<tbl_paketTemp> tbl_paketTemp { get; set; }
        public virtual DbSet<tbl_paketTempTy> tbl_paketTempTy { get; set; }
        public virtual DbSet<tbl_picture> tbl_picture { get; set; }
        public virtual DbSet<tbl_price> tbl_price { get; set; }
        public virtual DbSet<tbl_product> tbl_product { get; set; }
        public virtual DbSet<tbl_productHb> tbl_productHb { get; set; }
        public virtual DbSet<tbl_productsAltUrunHb> tbl_productsAltUrunHb { get; set; }
        public virtual DbSet<tbl_renk> tbl_renk { get; set; }
        public virtual DbSet<tbl_siparis> tbl_siparis { get; set; }
        public virtual DbSet<tbl_siparisTy> tbl_siparisTy { get; set; }
        public virtual DbSet<tbl_tyLink> tbl_tyLink { get; set; }
        public virtual DbSet<tbl_urun> tbl_urun { get; set; }
        public virtual DbSet<tbl_urunHb> tbl_urunHb { get; set; }
        public virtual DbSet<tbl_urunHbb> tbl_urunHbb { get; set; }
        public virtual DbSet<Tbl_Urunler> Tbl_Urunler { get; set; }
        public virtual DbSet<tbl_urunlertolink> tbl_urunlertolink { get; set; }
        public virtual DbSet<tbl_urunsku> tbl_urunsku { get; set; }
        public virtual DbSet<tbl_uruntosku> tbl_uruntosku { get; set; }
        public virtual DbSet<tbl_urunTy> tbl_urunTy { get; set; }
        public virtual DbSet<tbl_ürünkargoteslim> tbl_ürünkargoteslim { get; set; }
        public virtual DbSet<tbl_varyant> tbl_varyant { get; set; }
        public virtual DbSet<TeslimEdilemeyenSiparisler> TeslimEdilemeyenSiparislers { get; set; }
        public virtual DbSet<TeslimEdilenSiparisler> TeslimEdilenSiparislers { get; set; }
        public virtual DbSet<tyOrder> tyOrders { get; set; }
    }
}
