//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class HbKayitBazliMuhasebeServisi
    {
        public string transactionType { get; set; }
        public string status { get; set; }
        public string sku { get; set; }
        public string packageNumber { get; set; }
        public string orderNumber { get; set; }
        public string invoiceNumber { get; set; }
        public string orderItemNumber { get; set; }
        public string quantity { get; set; }
        public string amountValue { get; set; }
        public string amountCurrencyCode { get; set; }
        public string taxAmountValue { get; set; }
        public string taxAmountCurrencyCode { get; set; }
        public string netAmountValue { get; set; }
        public string netAmountCurrencyCode { get; set; }
        public string orderDate { get; set; }
        public string invoiceDate { get; set; }
        public string dueDate { get; set; }
        public string paymentDate { get; set; }
        public string invoiceExplanation { get; set; }
        public string merchantId { get; set; }
        public string isInvoice { get; set; }
        public string isIncome { get; set; }
        public string transactionTypeCategory { get; set; }
        public string productName { get; set; }
    }
}
