//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class iptalEdilenSiparisler
    {
        public int id { get; set; }
        public string lineItemId { get; set; }
        public string orderNumber { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
        public string cancelledBy { get; set; }
        public string cancelReasonCode { get; set; }
        public string merchantId { get; set; }
        public string quantity { get; set; }
        public string sku { get; set; }
        public string merchantSku { get; set; }
    }
}
