//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class picturesAltUrun
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string path { get; set; }
        public Nullable<int> @default { get; set; }
        public Nullable<int> sync { get; set; }
        public string path2 { get; set; }
        public Nullable<int> filesize { get; set; }
        public string supplier { get; set; }
        public string supplier_id { get; set; }
        public string supplier_code { get; set; }
        public string url { get; set; }
        public Nullable<int> downloaded { get; set; }
        public Nullable<int> option_id { get; set; }
        public Nullable<int> option_value_id { get; set; }
        public string group_code { get; set; }
        public string eticaret_id { get; set; }
        public Nullable<int> eticaret_sync { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string zebramo_picture_id { get; set; }
        public Nullable<int> flag { get; set; }
        public string eticaret_varyant_id { get; set; }
        public Nullable<int> sort_order_pov { get; set; }
        public Nullable<int> needion_id { get; set; }
        public string etsy_id { get; set; }
        public string bisifirat_id { get; set; }
        public string filemd5 { get; set; }
        public string TRIAL579 { get; set; }
    }
}
