//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ortakSiparis
    {
        public int paket_id { get; set; }
        public string sku { get; set; }
        public string siparisNo { get; set; }
        public string telefonNo { get; set; }
        public string mAd { get; set; }
        public string TAd { get; set; }
        public string fullAdres { get; set; }
        public string ozellikler1 { get; set; }
        public string kargoSirketi { get; set; }
        public string statu { get; set; }
        public string siparisTarihi { get; set; }
        public string sonGuncellemeTarihi { get; set; }
        public string pazarYeri { get; set; }
        public string ozellikler2 { get; set; }
        public string adet { get; set; }
        public string lineid { get; set; }
    }
}
