//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_buyboxTy
    {
        public int buyboxTy_id { get; set; }
        public string satici_id { get; set; }
        public string name { get; set; }
        public string discountedPrice { get; set; }
        public string sellingPrice { get; set; }
        public string originalPrice { get; set; }
        public string sellerScore { get; set; }
        public string link { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<bool> Otomanuel { get; set; }
        public string min { get; set; }
        public string max { get; set; }
        public Nullable<int> bizimsira { get; set; }
        public string bizimfiyat { get; set; }
        public string önceki { get; set; }
        public string sonraki { get; set; }
        public string barkod { get; set; }
    }
}
