//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_guncelFiyat
    {
        public int gFiyat_id { get; set; }
        public string urunSku { get; set; }
        public string urun_id { get; set; }
        public Nullable<decimal> guncelFiyat { get; set; }
        public string pazarYeri { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<bool> farkdurum { get; set; }
    }
}
