//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_iptalEdilenTy
    {
        public int iptalEdilenSiparisler_id { get; set; }
        public string orderNumber { get; set; }
        public string customerFirstName { get; set; }
        public string id { get; set; }
        public string cargoTrackingNumber { get; set; }
        public string cargoProviderName { get; set; }
        public string orderDate { get; set; }
        public string status { get; set; }
        public string totalPrice { get; set; }
    }
}
