//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_çop
    {
        public int paket_id { get; set; }
        public string urunAd { get; set; }
        public string mAd { get; set; }
        public string HBSKU { get; set; }
        public string kargoFirmasi { get; set; }
        public string siparisNo { get; set; }
        public string barkod { get; set; }
        public string paketNo { get; set; }
        public string adet { get; set; }
        public string fiyat { get; set; }
        public string vergiNo { get; set; }
        public string il { get; set; }
        public string ilçe { get; set; }
        public string semt { get; set; }
        public string tamadres { get; set; }
        public string property_value { get; set; }
        public string item_id { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public Nullable<bool> basilmaDurumu { get; set; }
        public string tAd { get; set; }
        public string magaza { get; set; }
    }
}
