//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int urun_id { get; set; }
        public string categoryId { get; set; }
        public string merchantIdHb { get; set; }
        public string attribute { get; set; }
        public string saticiSku { get; set; }
        public string varyantGrupIdHb { get; set; }
        public string urunAdi { get; set; }
        public Nullable<int> descreption_id { get; set; }
        public string barkod { get; set; }
        public string barcodeTy { get; set; }
        public string markaHb { get; set; }
        public Nullable<int> brandIdTy { get; set; }
        public string garantiSuresiHb { get; set; }
        public string agirlik { get; set; }
        public string adet { get; set; }
        public string currency_typeTy { get; set; }
        public string cargoCompanyIdTy { get; set; }
        public string attribute_nHb { get; set; }
        public string vatRateTy { get; set; }
        public Nullable<int> resim_id { get; set; }
        public Nullable<int> fiyat_id { get; set; }
        public Nullable<int> kargo_id { get; set; }
    
        public virtual tbl_cargo tbl_cargo { get; set; }
        public virtual tbl_picture tbl_picture { get; set; }
        public virtual tbl_price tbl_price { get; set; }
    }
}
