//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_altUrunler
    {
        public int altUrun_id { get; set; }
        public string altUrunAdi { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual tbl_urun tbl_urun { get; set; }
    }
}
