//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int musteri_id { get; set; }
        public string mAd { get; set; }
        public string mSoyad { get; set; }
        public string tel { get; set; }
        public string adres { get; set; }
    }
}
