//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparisTy
    {
        public int siparisTy_id { get; set; }
        public string magazaAd { get; set; }
        public string OrderNumber { get; set; }
        public string GrossAmount { get; set; }
        public string TotalDiscount { get; set; }
        public string TotalTyDiscount { get; set; }
        public string TaxNumber { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerId { get; set; }
        public string CustomerLastName { get; set; }
        public string Id { get; set; }
        public string CargoTrackingNumber { get; set; }
        public string CargoTrackingLink { get; set; }
        public string CargoSenderNumber { get; set; }
        public string CargoProviderName { get; set; }
        public string OrderDate { get; set; }
        public string TcIdentityNumber { get; set; }
        public string CurrencyCode { get; set; }
        public string ShipmentPackageStatus { get; set; }
        public string Status { get; set; }
        public string DeliveryType { get; set; }
        public string TimeSlotId { get; set; }
        public string ScheduledDeliveryStoreId { get; set; }
        public string EstimatedDeliveryStartDate { get; set; }
        public string EstimatedDeliveryEndDate { get; set; }
        public string TotalPrice { get; set; }
        public string DeliveryAddressType { get; set; }
        public string AgreedDeliveryDate { get; set; }
        public string FastDelivery { get; set; }
        public string OriginShipmentDate { get; set; }
        public string LastModifiedDate { get; set; }
        public string Commercial { get; set; }
        public string FastDeliveryType { get; set; }
        public string DeliveredByService { get; set; }
        public string InvoiceAddress_Id { get; set; }
        public string InvoiceAddress_FirstName { get; set; }
        public string InvoiceAddress_LastName { get; set; }
        public string InvoiceAddress_Company { get; set; }
        public string InvoiceAddress_Address1 { get; set; }
        public string InvoiceAddress_Address2 { get; set; }
        public string InvoiceAddress_City { get; set; }
        public string InvoiceAddress_CityCode { get; set; }
        public string InvoiceAddress_District { get; set; }
        public string InvoiceAddress_DistrictId { get; set; }
        public string InvoiceAddress_PostalCode { get; set; }
        public string InvoiceAddress_CountryCode { get; set; }
        public string InvoiceAddress_NeighborhoodId { get; set; }
        public string InvoiceAddress_Neighborhood { get; set; }
        public string InvoiceAddress_Phone { get; set; }
        public string InvoiceAddress_FullAddress { get; set; }
        public string InvoiceAddress_FullName { get; set; }
        public string InvoiceAddress_TaxOffice { get; set; }
        public string InvoiceAddress_TaxNumber { get; set; }
        public string InvoiceAddress_IsEInvoiceAvailable { get; set; }
        public string Lines_Quantity { get; set; }
        public string Lines_SalesCampaignId { get; set; }
        public string Lines_ProductSize { get; set; }
        public string Lines_MerchantSku { get; set; }
        public string Lines_ProductName { get; set; }
        public string Lines_ProductCode { get; set; }
        public string Lines_MerchantId { get; set; }
        public string Lines_Amount { get; set; }
        public string Lines_Discount { get; set; }
        public string Lines_TyDiscount { get; set; }
        public string Lines_CurrencyCode { get; set; }
        public string Lines_ProductColor { get; set; }
        public string Lines_Id { get; set; }
        public string Lines_Sku { get; set; }
        public string Lines_VatBaseAmount { get; set; }
        public string Lines_Barcode { get; set; }
        public string Lines_OrderLineItemStatusName { get; set; }
        public string Lines_Price { get; set; }
        public string PackageHistories_CreatedDate { get; set; }
        public string PackageHistories_Status { get; set; }
        public string ShipmentAddress_Id { get; set; }
        public string ShipmentAddress_FirstName { get; set; }
        public string ShipmentAddress_LastName { get; set; }
        public string ShipmentAddress_Company { get; set; }
        public string ShipmentAddress_Address1 { get; set; }
        public string ShipmentAddress_Address2 { get; set; }
        public string ShipmentAddress_City { get; set; }
        public string ShipmentAddress_CityCode { get; set; }
        public string ShipmentAddress_District { get; set; }
        public string ShipmentAddress_DistrictId { get; set; }
        public string ShipmentAddress_PostalCode { get; set; }
        public string ShipmentAddress_CountryCode { get; set; }
        public string ShipmentAddress_NeighborhoodId { get; set; }
        public string ShipmentAddress_Neighborhood { get; set; }
        public string ShipmentAddress_Phone { get; set; }
        public string ShipmentAddress_FullAddress { get; set; }
        public string ShipmentAddress_FullName { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string durum { get; set; }
    }
}
