//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_digerSaticiTagList
    {
        public int digerSaticiTag_id { get; set; }
        public string tag { get; set; }
        public Nullable<int> digerSaticiUrun_id { get; set; }
    
        public virtual tbl_digerSaticiUrun tbl_digerSaticiUrun { get; set; }
    }
}
