//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int id { get; set; }
        public string no { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string entegration { get; set; }
        public string status { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string company { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string mobil_phone { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string invoice_address { get; set; }
        public string invoice_city { get; set; }
        public string ship_address { get; set; }
        public string ship_city { get; set; }
        public Nullable<int> sync { get; set; }
        public string tax_office { get; set; }
        public string tax_number { get; set; }
        public string invoice_district { get; set; }
        public string invoice_fullname { get; set; }
        public string invoice_postcode { get; set; }
        public string invoice_tel { get; set; }
        public string invoice_gsm { get; set; }
        public string ship_district { get; set; }
        public string ship_fullname { get; set; }
        public string ship_postcode { get; set; }
        public string ship_tel { get; set; }
        public string ship_gsm { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> discount { get; set; }
        public string tc_id { get; set; }
        public string order_number { get; set; }
        public string supplier { get; set; }
        public string supplier_id { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public Nullable<int> invoice_print { get; set; }
        public Nullable<int> ship_print { get; set; }
        public string cargo_code { get; set; }
        public string cargo_fee_type { get; set; }
        public string cargo_company { get; set; }
        public Nullable<double> grand_total { get; set; }
        public Nullable<double> tax { get; set; }
        public string customer_code { get; set; }
        public string store_order_status { get; set; }
        public string store_order_status_name { get; set; }
        public string invoice_number { get; set; }
        public string ship_number { get; set; }
        public string username { get; set; }
        public Nullable<double> eur_rate { get; set; }
        public Nullable<double> usd_rate { get; set; }
        public Nullable<int> paymentType { get; set; }
        public string order_prefix { get; set; }
        public string delivery_method { get; set; }
        public string guid { get; set; }
        public Nullable<double> ship_price { get; set; }
        public string currencyType { get; set; }
        public Nullable<double> currency_rate { get; set; }
        public string erp_order_number { get; set; }
        public Nullable<int> erp_error { get; set; }
        public string erp_message { get; set; }
        public string bank_code { get; set; }
        public Nullable<int> installment { get; set; }
        public Nullable<int> marketing_sync { get; set; }
        public string invoice_country { get; set; }
        public string ship_country { get; set; }
        public string invoice_country_code { get; set; }
        public string ship_country_code { get; set; }
        public string supplier_order_id { get; set; }
        public string cargo_code2 { get; set; }
        public Nullable<int> cargo_sync { get; set; }
        public Nullable<double> total_commission_include_tax { get; set; }
        public string supplier_packet_id { get; set; }
        public Nullable<double> total_paid_price { get; set; }
        public Nullable<int> payment_status { get; set; }
        public string cargo_follow_url { get; set; }
        public string cargo_finally_statu { get; set; }
        public Nullable<System.DateTime> cargo_send_date { get; set; }
        public Nullable<double> coupon_price { get; set; }
        public string note { get; set; }
        public string cargo_barcode_raw { get; set; }
        public Nullable<int> cargo_packet_quantity { get; set; }
        public string cargo_error_message { get; set; }
        public string gib_number { get; set; }
        public Nullable<int> tracking_number_sync { get; set; }
        public Nullable<int> cargo_cancel_sync { get; set; }
        public string cargo_service_information { get; set; }
        public Nullable<int> morhipo_order_statu { get; set; }
        public string fulfillment { get; set; }
        public Nullable<int> fulfillment_sync { get; set; }
        public string fulfillment_code { get; set; }
        public string fulfillment_error_message { get; set; }
        public string ettn { get; set; }
        public Nullable<int> send_efatura { get; set; }
        public Nullable<int> cargo_delivery_status_sync { get; set; }
        public Nullable<int> create_common_label_sync { get; set; }
        public Nullable<int> order_process { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<System.DateTime> date_change { get; set; }
        public Nullable<int> is_fulfillment { get; set; }
        public string platform_reference_no { get; set; }
        public Nullable<int> is_partial { get; set; }
        public Nullable<double> grand_total_desi { get; set; }
        public Nullable<int> cargo_packet_type { get; set; }
        public string einvoice_error_message { get; set; }
        public Nullable<double> hb_discount_invoice { get; set; }
        public Nullable<int> mut_odeme { get; set; }
        public Nullable<int> mut_kargo { get; set; }
        public Nullable<int> mut_iptal { get; set; }
        public Nullable<int> total_product { get; set; }
        public Nullable<int> total_product_quantity { get; set; }
        public Nullable<int> mut_hizmet { get; set; }
        public string delivered_person_name { get; set; }
        public Nullable<System.DateTime> delivered_date { get; set; }
        public string shop_id { get; set; }
        public string store_id { get; set; }
        public Nullable<System.DateTime> preparation_time { get; set; }
        public Nullable<int> preparation_state_sync { get; set; }
        public Nullable<int> efatura_sync { get; set; }
        public Nullable<int> platform_serial_sync { get; set; }
    }
}
