//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_digerSaticiUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_digerSaticiUrun()
        {
            this.tbl_digerSaticiFiyat = new HashSet<tbl_digerSaticiFiyat>();
            this.tbl_digerSaticiTagList = new HashSet<tbl_digerSaticiTagList>();
            this.tbl_digerUrunSaticiNm = new HashSet<tbl_digerUrunSaticiNm>();
        }
    
        public int digerSaticiUrun_id { get; set; }
        public string name { get; set; }
        public string productId { get; set; }
        public string sku { get; set; }
        public string defaultSku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_digerSaticiFiyat> tbl_digerSaticiFiyat { get; set; }
        public virtual tbl_digerSaticiResim tbl_digerSaticiResim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_digerSaticiTagList> tbl_digerSaticiTagList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_digerUrunSaticiNm> tbl_digerUrunSaticiNm { get; set; }
    }
}
