//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ürünkargoteslim
    {
        public int id { get; set; }
        public string barkod { get; set; }
        public string kargogönderimtarihi { get; set; }
        public string siparişnumarası { get; set; }
        public string pazaryeri { get; set; }
        public string kullanici { get; set; }
        public string resimyol { get; set; }
    }
}
