//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productHb
    {
        public int productHb_id { get; set; }
        public string categoryId { get; set; }
        public string merchant { get; set; }
        public string merchantSku { get; set; }
        public string VaryantGroupID { get; set; }
        public string Barcode { get; set; }
        public string UrunAdi { get; set; }
        public string UrunAciklamasi { get; set; }
        public string Marka { get; set; }
        public string GarantiSuresi { get; set; }
        public string kg { get; set; }
        public string tax_vat_rate { get; set; }
        public string price { get; set; }
        public string stock { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string renk_variant_property { get; set; }
        public string ebatlar_variant_property { get; set; }
        public string markaTy { get; set; }
        public string kategoriTy { get; set; }
        public string listeFiyatiTy { get; set; }
        public string satisFiyatiTy { get; set; }
    }
}
