//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_urun()
        {
            this.tbl_altUrunler = new HashSet<tbl_altUrunler>();
            this.tbl_log = new HashSet<tbl_log>();
        }
    
        public int urun_id { get; set; }
        public string urunAd { get; set; }
        public string altAd { get; set; }
        public string barkod { get; set; }
        public string varyantBarkod { get; set; }
        public Nullable<int> urunKdv { get; set; }
        public Nullable<int> yil { get; set; }
        public string aciklama { get; set; }
        public string urunKodu { get; set; }
        public Nullable<int> stok { get; set; }
        public Nullable<bool> stokDurum { get; set; }
        public Nullable<bool> urunDurum { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> mFiyat_id { get; set; }
        public Nullable<int> marka_id { get; set; }
        public Nullable<int> fatura_id { get; set; }
        public Nullable<int> ozellik_id { get; set; }
        public Nullable<int> durum_id { get; set; }
        public string eklemeTipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_altUrunler> tbl_altUrunler { get; set; }
        public virtual tbl_durum tbl_durum { get; set; }
        public virtual tbl_fatura tbl_fatura { get; set; }
        public virtual tbl_kategori tbl_kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_log> tbl_log { get; set; }
        public virtual tbl_magazaFiyatlari tbl_magazaFiyatlari { get; set; }
        public virtual tbl_marka tbl_marka { get; set; }
    }
}
