//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_buybox
    {
        public int buybox_id { get; set; }
        public Nullable<int> bizimSira { get; set; }
        public string ürün_ad { get; set; }
        public Nullable<decimal> bizimFiyat { get; set; }
        public Nullable<decimal> minFiyat { get; set; }
        public Nullable<decimal> maxFiyat { get; set; }
        public string Sku { get; set; }
        public string Rank { get; set; }
        public string MerchantName { get; set; }
        public string Price { get; set; }
        public string DispatchTime { get; set; }
        public string MerchantRating { get; set; }
        public string onceki { get; set; }
        public string sonraki { get; set; }
        public Nullable<decimal> öneri { get; set; }
        public Nullable<bool> Otomanuel { get; set; }
        public Nullable<decimal> fark { get; set; }
        public Nullable<decimal> endusukfiyat { get; set; }
        public Nullable<decimal> baslangıcfiyat { get; set; }
        public Nullable<bool> Farkdurum { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<decimal> GuncelFiyat { get; set; }
        public Nullable<bool> elleotomatik { get; set; }
        public Nullable<int> islemsayisi { get; set; }
    }
}
