//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_fatura()
        {
            this.tbl_urun = new HashSet<tbl_urun>();
        }
    
        public int fatura_id { get; set; }
        public Nullable<decimal> eFaturaSeri { get; set; }
        public Nullable<decimal> eArsivSeri { get; set; }
        public Nullable<decimal> kargoKodu { get; set; }
        public Nullable<decimal> kargoVergiNo { get; set; }
        public Nullable<int> urun_id { get; set; }
        public string webSiteUrl { get; set; }
        public string kdvIstisnaDurum { get; set; }
        public string faturaTipi { get; set; }
        public string eFaturaTipi { get; set; }
        public Nullable<int> firma_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
    
        public virtual tbl_musteri tbl_musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_urun> tbl_urun { get; set; }
    }
}
