//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log
    {
        public int log_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<System.TimeSpan> zaman { get; set; }
        public Nullable<int> kullanici_id { get; set; }
    
        public virtual tbl_kullanici tbl_kullanici { get; set; }
        public virtual tbl_urun tbl_urun { get; set; }
    }
}
