//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_musteri()
        {
            this.tbl_fatura = new HashSet<tbl_fatura>();
        }
    
        public int firma_id { get; set; }
        public Nullable<decimal> vkn { get; set; }
        public string vergiDairesi { get; set; }
        public string alias { get; set; }
        public string firmaAdi { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string adres { get; set; }
        public string mail { get; set; }
        public Nullable<decimal> tel { get; set; }
        public string sabitSiparisNotu { get; set; }
        public string pazarYeri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_fatura> tbl_fatura { get; set; }
    }
}
