//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hizliEkleHb
    {
        public int hue_id { get; set; }
        public string ProductName { get; set; }
        public string MerchantSku { get; set; }
        public string Barcode { get; set; }
        public string Price { get; set; }
        public string Stock { get; set; }
    }
}
