//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_uruntosku
    {
        public int id { get; set; }
        public string sku { get; set; }
        public string ürünad { get; set; }
        public string resimyol { get; set; }
        public Nullable<bool> durum { get; set; }
    }
}
