//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urunTy
    {
        public int urunty_id { get; set; }
        public string OrderNumber { get; set; }
        public string GrossAmount { get; set; }
        public string TotalDiscount { get; set; }
        public string TotalTyDiscount { get; set; }
        public string TaxNumber { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerId { get; set; }
        public string CustomerLastName { get; set; }
        public string Id { get; set; }
        public string CargoTrackingNumber { get; set; }
        public string CargoTrackingLink { get; set; }
        public string CargoSenderNumber { get; set; }
        public string CargoProviderName { get; set; }
        public string OrderDate { get; set; }
        public string TcIdentityNumber { get; set; }
        public string CurrencyCode { get; set; }
        public string ShipmentPackageStatus { get; set; }
        public string Status { get; set; }
        public string DeliveryType { get; set; }
        public string TimeSlotId { get; set; }
        public string ScheduledDeliveryStoreId { get; set; }
        public string EstimatedDeliveryStartDate { get; set; }
        public string EstimatedDeliveryEndDate { get; set; }
        public string TotalPrice { get; set; }
        public string DeliveryAddressType { get; set; }
        public string AgreedDeliveryDate { get; set; }
        public string FastDelivery { get; set; }
        public string OriginShipmentDate { get; set; }
        public string LastModifiedDate { get; set; }
        public string Commercial { get; set; }
        public string FastDeliveryType { get; set; }
        public string DeliveredByService { get; set; }
        public string InvoiceAddress_Id { get; set; }
        public string InvoiceAddress_FirstName { get; set; }
        public string InvoiceAddress_LastName { get; set; }
        public string InvoiceAddress_Company { get; set; }
        public string InvoiceAddress_Address1 { get; set; }
        public string InvoiceAddress_Address2 { get; set; }
        public string InvoiceAddress_City { get; set; }
        public string InvoiceAddress_CityCode { get; set; }
        public string InvoiceAddress_District { get; set; }
        public string InvoiceAddress_DistrictId { get; set; }
        public string InvoiceAddress_PostalCode { get; set; }
        public string InvoiceAddress_CountryCode { get; set; }
        public string InvoiceAddress_NeighborhoodId { get; set; }
        public string InvoiceAddress_Neighborhood { get; set; }
        public string InvoiceAddress_Phone { get; set; }
        public string InvoiceAddress_FullAddress { get; set; }
        public string InvoiceAddress_FullName { get; set; }
        public string InvoiceAddress_TaxOffice { get; set; }
        public string InvoiceAddress_TaxNumber { get; set; }
        public string InvoiceAddress_IsEInvoiceAvailable { get; set; }
        public string LineItemPrice { get; set; }
        public string LineItemDiscount { get; set; }
        public string LineItemTyDiscount { get; set; }
        public string Quantity { get; set; }
        public string SalesCampaignId { get; set; }
        public string ProductSize { get; set; }
        public string MerchantSku { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string MerchantId { get; set; }
        public string Amount { get; set; }
        public string Discount { get; set; }
        public string TyDiscount { get; set; }
        public string CurrencyCodety { get; set; }
        public string ProductColor { get; set; }
        public string Idty { get; set; }
        public string Sku { get; set; }
        public string VatBaseAmount { get; set; }
        public string Barcode { get; set; }
        public string OrderLineItemStatusName { get; set; }
        public string Price { get; set; }
        public string CreatedDate { get; set; }
        public string Statusty { get; set; }
        public string Idk { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public string District { get; set; }
        public string DistrictId { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string NeighborhoodId { get; set; }
        public string Neighborhood { get; set; }
        public string Phone { get; set; }
        public string FullAddress { get; set; }
        public string FullName { get; set; }
    }
}
