//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kategorilerHb
    {
        public int categoryId { get; set; }
        public string name { get; set; }
        public string displayName { get; set; }
        public Nullable<decimal> parentCategoryId { get; set; }
        public string paths { get; set; }
        public string leaf { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public Nullable<int> sortId { get; set; }
        public string imageURL { get; set; }
        public string available { get; set; }
        public string productTypes_name { get; set; }
        public Nullable<decimal> productTypes_TypeId { get; set; }
    }
}
