//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullohbuybox
    {
        public int id { get; set; }
        public string sku { get; set; }
        public string kad { get; set; }
        public Nullable<decimal> min { get; set; }
        public Nullable<decimal> max { get; set; }
        public Nullable<decimal> fark { get; set; }
        public Nullable<bool> otomanuel { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
