//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeslimEdilemeyenSiparisler
    {
        public int pid { get; set; }
        public string Barcode { get; set; }
        public string PackageNumber { get; set; }
        public string OrderNumber { get; set; }
        public string MerchantId { get; set; }
        public Nullable<System.DateTime> UndeliveredDate { get; set; }
        public string UndeliveredReason { get; set; }
        public string lineitemid { get; set; }
    }
}
