//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseToXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class tyOrder
    {
        public string shipmentAdressFullName { get; set; }
        public string shipmentAdressFullAdress { get; set; }
        public string orderNumber { get; set; }
        public string grossAmount { get; set; }
        public string totalDiscount { get; set; }
        public string totalTyDiscount { get; set; }
        public string invoiceAdressFullNAme { get; set; }
        public string invoiceAdressFullAdress { get; set; }
        public string customerFirstNAme { get; set; }
        public string customerEmail { get; set; }
        public string customerId { get; set; }
        public string cargoTrackingNumber { get; set; }
        public string cargoTrackingLink { get; set; }
        public string cargoSenderNumber { get; set; }
        public string cargoProviderName { get; set; }
        public string quantity { get; set; }
        public string salesCampaignId { get; set; }
        public string productSize { get; set; }
        public string merchantSku { get; set; }
        public string productName { get; set; }
        public string productCode { get; set; }
        public string merchantID { get; set; }
        public string amount { get; set; }
        public string discount { get; set; }
        public string tyDiscount { get; set; }
        public string currencyCode { get; set; }
        public string productColor { get; set; }
        public int id { get; set; }
        public string sku { get; set; }
        public string vatBaseAmount { get; set; }
        public string barcode { get; set; }
        public string orderLineItemStatusName { get; set; }
        public string price { get; set; }
        public string OrderDate { get; set; }
        public string tcIdentityNumber { get; set; }
        public string shipmentPackageStatus { get; set; }
        public string status { get; set; }
        public string deliveryType { get; set; }
        public string timeSlotId { get; set; }
        public string scheduleDeliveryStoreId { get; set; }
        public string estimatedDeliveryStartDate { get; set; }
        public string estimatedDeliveryEndDate { get; set; }
        public string totalPrice { get; set; }
        public string deliveryAddressType { get; set; }
        public string agreedDeliveryDate { get; set; }
        public string agreedDeliveryDateExtendible { get; set; }
        public string extendedAgreedDeliveryDate { get; set; }
        public string agreedDeliveryExtensionStartDate { get; set; }
        public string agreedDeliveryExtensionEndDate { get; set; }
        public string fastDelivery { get; set; }
        public string fastDeliveryType { get; set; }
        public string originShipmentDate { get; set; }
        public string lastModifiedDate { get; set; }
        public string commercial { get; set; }
        public string deliveredByService { get; set; }
    }
}
