using System;
using System.Collections.Generic;

namespace DatabaseToXml.Models
{
    public partial class TblOrder
    {
        public int Id { get; set; }
        public string? No { get; set; }
        public DateTime? Datetime { get; set; }
        public string? Entegration { get; set; }
        public string? Status { get; set; }
        public int? CustomerId { get; set; }
        public string? Company { get; set; }
        public string? Firstname { get; set; }
        public string? Lastname { get; set; }
        public string? Email { get; set; }
        public string? MobilPhone { get; set; }
        public string? Telephone { get; set; }
        public string? Fax { get; set; }
        public string? InvoiceAddress { get; set; }
        public string? InvoiceCity { get; set; }
        public string? ShipAddress { get; set; }
        public string? ShipCity { get; set; }
        public int? Sync { get; set; }
        public string? TaxOffice { get; set; }
        public string? TaxNumber { get; set; }
        public string? InvoiceDistrict { get; set; }
        public string? InvoiceFullname { get; set; }
        public string? InvoicePostcode { get; set; }
        public string? InvoiceTel { get; set; }
        public string? InvoiceGsm { get; set; }
        public string? ShipDistrict { get; set; }
        public string? ShipFullname { get; set; }
        public string? ShipPostcode { get; set; }
        public string? ShipTel { get; set; }
        public string? ShipGsm { get; set; }
        public double? Total { get; set; }
        public double? Discount { get; set; }
        public string? TcId { get; set; }
        public string? OrderNumber { get; set; }
        public string? Supplier { get; set; }
        public string? SupplierId { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public DateTime? ShipDate { get; set; }
        public int? InvoicePrint { get; set; }
        public int? ShipPrint { get; set; }
        public string? CargoCode { get; set; }
        public string? CargoFeeType { get; set; }
        public string? CargoCompany { get; set; }
        public double? GrandTotal { get; set; }
        public double? Tax { get; set; }
        public string? CustomerCode { get; set; }
        public string? StoreOrderStatus { get; set; }
        public string? StoreOrderStatusName { get; set; }
        public string? InvoiceNumber { get; set; }
        public string? ShipNumber { get; set; }
        public string? Username { get; set; }
        public double? EurRate { get; set; }
        public double? UsdRate { get; set; }
        public int? PaymentType { get; set; }
        public string? OrderPrefix { get; set; }
        public string? DeliveryMethod { get; set; }
        public string? Guid { get; set; }
        public double? ShipPrice { get; set; }
        public string? CurrencyType { get; set; }
        public double? CurrencyRate { get; set; }
        public string? ErpOrderNumber { get; set; }
        public int? ErpError { get; set; }
        public string? ErpMessage { get; set; }
        public string? BankCode { get; set; }
        public int? Installment { get; set; }
        public int? MarketingSync { get; set; }
        public string? InvoiceCountry { get; set; }
        public string? ShipCountry { get; set; }
        public string? InvoiceCountryCode { get; set; }
        public string? ShipCountryCode { get; set; }
        public string? SupplierOrderId { get; set; }
        public string? CargoCode2 { get; set; }
        public int? CargoSync { get; set; }
        public double? TotalCommissionIncludeTax { get; set; }
        public string? SupplierPacketId { get; set; }
        public double? TotalPaidPrice { get; set; }
        public int? PaymentStatus { get; set; }
        public string? CargoFollowUrl { get; set; }
        public string? CargoFinallyStatu { get; set; }
        public DateTime? CargoSendDate { get; set; }
        public double? CouponPrice { get; set; }
        public string? Note { get; set; }
        public string? CargoBarcodeRaw { get; set; }
        public int? CargoPacketQuantity { get; set; }
        public string? CargoErrorMessage { get; set; }
        public string? GibNumber { get; set; }
        public int? TrackingNumberSync { get; set; }
        public int? CargoCancelSync { get; set; }
        public string? CargoServiceInformation { get; set; }
        public int? MorhipoOrderStatu { get; set; }
        public string? Fulfillment { get; set; }
        public int? FulfillmentSync { get; set; }
        public string? FulfillmentCode { get; set; }
        public string? FulfillmentErrorMessage { get; set; }
        public string? Ettn { get; set; }
        public int? SendEfatura { get; set; }
        public int? CargoDeliveryStatusSync { get; set; }
        public int? CreateCommonLabelSync { get; set; }
        public int? OrderProcess { get; set; }
        public DateTime? DateAdd { get; set; }
        public DateTime? DateChange { get; set; }
        public int? IsFulfillment { get; set; }
        public string? PlatformReferenceNo { get; set; }
        public int? IsPartial { get; set; }
        public double? GrandTotalDesi { get; set; }
        public int? CargoPacketType { get; set; }
        public string? EinvoiceErrorMessage { get; set; }
        public double? HbDiscountInvoice { get; set; }
        public int? MutOdeme { get; set; }
        public int? MutKargo { get; set; }
        public int? MutIptal { get; set; }
        public int? TotalProduct { get; set; }
        public int? TotalProductQuantity { get; set; }
        public int? MutHizmet { get; set; }
        public string? DeliveredPersonName { get; set; }
        public DateTime? DeliveredDate { get; set; }
        public string? ShopId { get; set; }
        public string? StoreId { get; set; }
        public DateTime? PreparationTime { get; set; }
        public int? PreparationStateSync { get; set; }
        public int? EfaturaSync { get; set; }
        public int? PlatformSerialSync { get; set; }
    }
}
