using System;
using System.Collections.Generic;

namespace DatabaseToXml.Models
{
    public partial class TblSiparisTy
    {
        public int SiparisTyId { get; set; }
        public string? MagazaAd { get; set; }
        public string? OrderNumber { get; set; }
        public string? GrossAmount { get; set; }
        public string? TotalDiscount { get; set; }
        public string? TotalTyDiscount { get; set; }
        public string? TaxNumber { get; set; }
        public string? CustomerFirstName { get; set; }
        public string? CustomerEmail { get; set; }
        public string? CustomerId { get; set; }
        public string? CustomerLastName { get; set; }
        public string? Id { get; set; }
        public string? CargoTrackingNumber { get; set; }
        public string? CargoTrackingLink { get; set; }
        public string? CargoSenderNumber { get; set; }
        public string? CargoProviderName { get; set; }
        public string? OrderDate { get; set; }
        public string? TcIdentityNumber { get; set; }
        public string? CurrencyCode { get; set; }
        public string? ShipmentPackageStatus { get; set; }
        public string? Status { get; set; }
        public string? DeliveryType { get; set; }
        public string? TimeSlotId { get; set; }
        public string? ScheduledDeliveryStoreId { get; set; }
        public string? EstimatedDeliveryStartDate { get; set; }
        public string? EstimatedDeliveryEndDate { get; set; }
        public string? TotalPrice { get; set; }
        public string? DeliveryAddressType { get; set; }
        public string? AgreedDeliveryDate { get; set; }
        public string? FastDelivery { get; set; }
        public string? OriginShipmentDate { get; set; }
        public string? LastModifiedDate { get; set; }
        public string? Commercial { get; set; }
        public string? FastDeliveryType { get; set; }
        public string? DeliveredByService { get; set; }
        public string? InvoiceAddressId { get; set; }
        public string? InvoiceAddressFirstName { get; set; }
        public string? InvoiceAddressLastName { get; set; }
        public string? InvoiceAddressCompany { get; set; }
        public string? InvoiceAddressAddress1 { get; set; }
        public string? InvoiceAddressAddress2 { get; set; }
        public string? InvoiceAddressCity { get; set; }
        public string? InvoiceAddressCityCode { get; set; }
        public string? InvoiceAddressDistrict { get; set; }
        public string? InvoiceAddressDistrictId { get; set; }
        public string? InvoiceAddressPostalCode { get; set; }
        public string? InvoiceAddressCountryCode { get; set; }
        public string? InvoiceAddressNeighborhoodId { get; set; }
        public string? InvoiceAddressNeighborhood { get; set; }
        public string? InvoiceAddressPhone { get; set; }
        public string? InvoiceAddressFullAddress { get; set; }
        public string? InvoiceAddressFullName { get; set; }
        public string? InvoiceAddressTaxOffice { get; set; }
        public string? InvoiceAddressTaxNumber { get; set; }
        public string? InvoiceAddressIsEinvoiceAvailable { get; set; }
        public string? LinesQuantity { get; set; }
        public string? LinesSalesCampaignId { get; set; }
        public string? LinesProductSize { get; set; }
        public string? LinesMerchantSku { get; set; }
        public string? LinesProductName { get; set; }
        public string? LinesProductCode { get; set; }
        public string? LinesMerchantId { get; set; }
        public string? LinesAmount { get; set; }
        public string? LinesDiscount { get; set; }
        public string? LinesTyDiscount { get; set; }
        public string? LinesCurrencyCode { get; set; }
        public string? LinesProductColor { get; set; }
        public string? LinesId { get; set; }
        public string? LinesSku { get; set; }
        public string? LinesVatBaseAmount { get; set; }
        public string? LinesBarcode { get; set; }
        public string? LinesOrderLineItemStatusName { get; set; }
        public string? LinesPrice { get; set; }
        public string? PackageHistoriesCreatedDate { get; set; }
        public string? PackageHistoriesStatus { get; set; }
        public string? ShipmentAddressId { get; set; }
        public string? ShipmentAddressFirstName { get; set; }
        public string? ShipmentAddressLastName { get; set; }
        public string? ShipmentAddressCompany { get; set; }
        public string? ShipmentAddressAddress1 { get; set; }
        public string? ShipmentAddressAddress2 { get; set; }
        public string? ShipmentAddressCity { get; set; }
        public string? ShipmentAddressCityCode { get; set; }
        public string? ShipmentAddressDistrict { get; set; }
        public string? ShipmentAddressDistrictId { get; set; }
        public string? ShipmentAddressPostalCode { get; set; }
        public string? ShipmentAddressCountryCode { get; set; }
        public string? ShipmentAddressNeighborhoodId { get; set; }
        public string? ShipmentAddressNeighborhood { get; set; }
        public string? ShipmentAddressPhone { get; set; }
        public string? ShipmentAddressFullAddress { get; set; }
        public string? ShipmentAddressFullName { get; set; }
        public DateTime? KayitTarihi { get; set; }
        public string? Durum { get; set; }
    }
}
